name: publish

on: [push]

jobs:
  assignment1-image:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        docker build . -t docker.io/nouranhady/assignment1-image2:latest
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker push docker.io/nouranhady/assignment1-image:latest
